# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Arkylin's Blog
subtitle: A Student Blog.
description: Arkylin's Blog
keywords: Arkylin's Blog,Arkylin,Blog,Notes,Student
author: 凌
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.xyz.blue
root: /
permalink: :year/:month/:day/:translate_title.html
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: '*/*/*.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 学习
category_map:
  {
    学习: Study,
    程序: Programs,
    生活随笔: Life,
    常用配置: Common,
    技巧: Skill,
    代码: Code,
    安卓开发: Android_develop,
    测评: Evaluation,
    阿里云: Aliyun,
    脚本: Scripts,
    解决方案: Solution
    }
tag_map:
  {
    学习: Study,
    生活随笔: Life,
    常用配置: Common,
    技巧: Skill,
    代码: Code,
    安卓开发: Android-Develop,
    页面: Pages,
    Ipv6隧道: Ipv6-Tunnel,
    隧道: Tunnel,
    超级管理员: Super-Administrator,
    电信: Telecommunications,
    密码: Password,
    通信: Communication,
    转义: Escape,
    转义字符: Escape-Character,
    小内存: Small-Memory,
    虚拟内存: Virtual-Memory,
    优化参数: Optimize-Parameters,
    跳转: Jump,
    花粉: Pollen,
    花粉俱乐部: Pollen-Club,
    菜单: Menu,
    文本操作菜单: Text-Operation-Menu,
    华为: Huawei,
    阿里云: Aliyun,
    加密: Encryption,
    默认用户: Default-User,
    脚本: Script,
    安卓: Android,
    编译: Compile,
    查询: Inquire,
    端口: Port,
    附件: Annex,
    静态地址: Static-Address,
    静态页面: Static-Pages,
    手写字体: Handwriting-Font,
    树莓派: Raspberry-Pie,
    水: Water,
    特效: Special-Effects,
    微博: Weibo,
    运维编排: Operation-And-Maintenance,
    字体: Fonts,
    解决方案: Solution,
    人人通: renrentong,
    助手: Assistant,
    程序: Programs
    }

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
#use_date_for_updated: false
updated_option: date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly
#theme: Kylin

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
  #type: ali-oss
  #region: oss-cn-hongkong
  #accessKeyId: LTAI4FwbRdqkMc31MZhTjt1e
  #accessKeySecret: d97WDrK23jskRR1GTgJdfW7D5AkXCd
  #bucket: kylin-blog
deploy:
  type: git
  repository: 
    coding: git@e.coding.net:iloveyou/blog/blog.git
  branch: master

#Title Translate
translate_title:
  translate_way: google  # google,youdao,baidu_with_appid,baidu_no_appid
  youdao_api_key: '' # Your youdao_api_key
  youdao_keyfrom: xxxx-blog # Your youdao_keyfrom
  is_need_proxy: false     # true | false
  proxy_url: http://localhost:50018 # Your proxy_url
  baidu_appid: '' # Your baidu_appid
  baidu_appkey: '' # Your baidu_appkey

#RSS Feed
feed:
  type: atom
  path: RSS.xml
  limit: 0