# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set Env
      run: |
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install setuptools
        sudo pip3 install coscmd
        whereis coscmd
    - name: Create HTML files
      run: |
        npm install
        node_modules/.bin/hexo g
    - name: Set COS BUCKET
      run: |
        COS_SECRET_ID='${{ secrets.COS_SECRET_ID }}'
        COS_SECRET_KEY='${{ secrets.COS_SECRET_KEY }}'
        COS_BUCKET_NAME='${{ secrets.COS_BUCKET_NAME }}'
        COS_BUCKET_REGION='${{ secrets.COS_BUCKET_REGION }}'

        coscmd config -a ${COS_SECRET_ID} -s ${COS_SECRET_KEY} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_REGION}
        coscmd upload ./_config.yml ./
