# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: 配置 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 设置初始环境
      run: |
        sudo wget http://gosspublic.alicdn.com/ossutil/1.6.18/ossutil64
        sudo chmod 755 ossutil64
    - name: 安装扩展
      run: |
        npm install
    - name: 生成静态页面
      run: |
        node_modules/.bin/hexo g
    - name: 设置储存桶
      run: |
        OSS_ACCESSKEY_ID='${{ secrets.OSS_ACCESSKEY_ID }}'
        OSS_ACCESSKEY_SECRET='${{ secrets.OSS_ACCESSKEY_SECRET }}'
        OSS_BUCKET_NAME='${{ secrets.OSS_BUCKET_NAME }}'
        OSS_BUCKET_NAME_FINAL='oss://'${OSS_BUCKET_NAME}
        OSS_BUCKET_REGION='${{ secrets.OSS_BUCKET_REGION }}'
        OSS_BUCKET_REGION_FINAL=${OSS_BUCKET_REGION}'.aliyuncs.com'
        ./ossutil64 config -e ${OSS_BUCKET_REGION_FINAL} -i ${OSS_ACCESSKEY_ID} -k ${OSS_ACCESSKEY_SECRET} -L CH
    - name: 上传文件
      run: |
        echo ${OSS_BUCKET_NAME_FINAL}
        ./ossutil64 cp -r -u public ${OSS_BUCKET_NAME_FINAL}
    - name: 删除密钥文件
      run: |
        if [ -e "~/.ossutilconfig" ]; then
          sudo rm -rf ~/.ossutilconfig
          echo "文件已删除"
        else
          echo "文件已消失"
        fi