# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: 配置 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 设置初始环境
      run: |
        sudo wget http://gosspublic.alicdn.com/ossutil/1.6.18/ossutil64
        sudo chmod 755 ossutil64
    - name: 安装扩展
      run: |
        npm install
    - name: 生成静态页面
      run: |
        node_modules/.bin/hexo g
    - name: 设置储存桶
      run: |
        ./ossutil64 config -e ${{ secrets.OSS_BUCKET_REGION }}.aliyuncs.com -i ${{ secrets.OSS_ACCESSKEY_ID }} -k ${{ secrets.OSS_ACCESSKEY_SECRET }} -L CH
    - name: 上传文件
      run: |
        ./ossutil64 cp -r -u public oss://${{ secrets.OSS_BUCKET_NAME }}
    - name: 删除密钥文件
      run: |
        if [ -e "~/.ossutilconfig" ]; then
          sudo rm -rf ~/.ossutilconfig
          echo "文件已删除"
        else
          echo "文件已消失"
        fi